{% set version = "0.3.1" %}

package:
  name: ncflag
  version: {{ version }}

source:
  url: https://github.com/5tefan/ncflag/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7f2a291e9af5b02f89838d3cef2e971c7d97db9e5737c3174fa48d4189db8f65

build:
  noarch: python
  entry_points:
    - "ncflag = ncflag.cli:cli"
  number: 0
  script: 
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - pypandoc
  run:
    - python >=3.7
    - numpy
    - netcdf4
    - click >=7.0,<8.0

test:
  imports:
    - ncflag
  requires:
    - pip
  source_files:
    - test/
  commands:
    - pip check
    - python -m unittest discover -s .

about:
  home: https://github.com/5tefan/ncflag
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Interface for binary flags in data.'
  description: |
    ncflag is an interface for binary flag vectors in data. For example,
    ommonly used for quality flags. A set of
    compatible binary flag vectors are associated with flag_meanings, 
    flag_values, and possibly flag_masks metadata. These flags are 
    described in the CF-Conventions 
    http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#flags
    The library is oriented towards netCDF data files, but could be 
    used in other contexts as well.
  doc_url: https://github.com/5tefan/ncflag
  dev_url: https://github.com/5tefan/ncflag

extra:
  recipe-maintainers:
    - khallock
    - 5tefan
